spring.application.name=gatewayserver
eureka.instance.preferIpAddress=true
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka/

#info config for eureka server
info.app.name=${spring.application.name}
info.app.description=Gateway Server for routing requests to microservices
info.app.version=1.0.0
